# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Huy Le's Blog
tagline:          If you write, it will still be there forever
url:              http://lephukhanhhuy.github.io
paginate:         1
baseurl:          /
author:
  name:           Huy Le
  url:            http://lephukhanhhuy.github.io
  email:          lephukhanhhuy@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
